apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  type: standalone
  image: "nacos/nacos-server:{{ .Values.nacosVersion }}"
  replicas: 1
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
